### ISSUE TITLE
Setup Bungeecord

### ISSUE THREAD

**Issue by RealCalumPlays** [Skungee/Skungee#210] opened 2020-10-19 19:19 UTC
[21:16:24 INFO]: [Skungee] [Skungee] Severe Error: [ServerSocket couldn't be created on port: 25584]
[21:16:24 INFO]:
[21:16:24 INFO]: [Skungee] Something went wrong within Skungee.
[21:16:24 INFO]: [Skungee] Please report this error to the developers of Skungee so we can fix this from happening in the future.
[21:16:24 INFO]:
[21:16:24 INFO]: [Skungee] Report this at https://github.com/TheLimeGlass/Skungee/issues. You can also message one of the Skungee developers.
[21:16:24 INFO]:
[21:16:24 INFO]: [Skungee] Stack trace:
[21:16:24 INFO]: [Skungee] java.net.BindException: Cannot assign requested address (Bind failed)
[21:16:24 INFO]: [Skungee] at java.net.PlainSocketImpl.socketBind(Native Method)
[21:16:24 INFO]: [Skungee] at java.net.AbstractPlainSocketImpl.bind(AbstractPlainSocketImpl.java:387)
[21:16:24 INFO]: [Skungee] at java.net.ServerSocket.bind(ServerSocket.java:390)
[21:16:24 INFO]: [Skungee] at java.net.ServerSocket.<init>(ServerSocket.java:252)
[21:16:24 INFO]: [Skungee] at me.limeglass.skungee.bungeecord.Skungee.connect(Skungee.java:162)
[21:16:24 INFO]: [Skungee] at me.limeglass.skungee.bungeecord.Skungee.onEnable(Skungee.java:124)
[21:16:24 INFO]: [Skungee] at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:300)
[21:16:24 INFO]: [Skungee] at net.md_5.bungee.BungeeCord.start(BungeeCord.java:289)
[21:16:24 INFO]: [Skungee] at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:62)
[21:16:24 INFO]: [Skungee] at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
[21:16:24 INFO]:
[21:16:24 INFO]: [Skungee] Information:
[21:16:24 INFO]: [Skungee] Skungee: 1.0.15
[21:16:24 INFO]: [Skungee] Bungee: git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:c1ac7d5:377
[21:16:24 INFO]: [Skungee] Game version: 1.8.x, 1.9.x, 1.10.x, 1.11.x, 1.12.x, 1.13.x, 1.14.x, 1.15.x, 1.16.x
[21:16:24 INFO]: [Skungee] Protocol version: 753
[21:16:24 INFO]: [Skungee] Java: 1.8.0_262 (OpenJDK 64-Bit Server VM 25.262-b10)
[21:16:24 INFO]: [Skungee] OS: Linux amd64 5.4.0-48-generic
[21:16:24 INFO]:
[21:16:24 INFO]: [Skungee] Thread: Thread[main,5,main]
[21:16:24 INFO]: [Skungee] Cause: [ServerSocket couldn't be created on port: 25584]
[21:16:24 INFO]:
[21:16:24 INFO]: [Skungee] End of Error.

Getting this error. The port is open btw.

**Comment by brobie1kanobi** [comment] 2020-11-26 23:14
@RealCalumPlays It seems that much is still broke with the issues being reported, but the 2.0.0 version did fix this and has no errors connecting.

**Comment by brobie1kanobi** [comment] 2020-11-26 23:22
Duplicate of #200

**Closed** 2020-11-27 05:27 UTC
