### ISSUE TITLE
Player's bungeecord server returns <none>

### ISSUE THREAD

**Issue by JimmyTDM** [Skungee/Skungee#164] opened 2020-06-06 13:49 UTC
So I'm using skungee 1.0.13 (latest version) and when I try to execute any skungee effect like send player or message player's bungeecord server it doesnt do anything, I tried downgrading to 1.0.12 and still, it doesn't work, any advice on what to do? /server works, but nothing else related to skungee with skript (in the bungeecord console it does work)

**Comment by TheLimeGlass** [comment] 2020-08-10 13:54
Most likely a duplicate of #149 and others

**Closed by TheLimeGlass** 2020-08-10 13:54 UTC
