### ISSUE TITLE
%current server% returns  <none>

### ISSUE THREAD

**Issue by melinstagibson** [Skungee/Skungee#46] opened 2019-01-22 20:42 UTC
title says it all i guess, am on the latest version of skungee, paperspigot (1.13.2), bungeecord and  skript (2.3.2)

also this worked up to now, idk if the skungee or the bungee update i did today broke it...

**Comment by TrademarkTM** [comment] 2019-02-07 19:46
I am having the same problem.
Anything that has to do with BungeeCord doesn't work. Skungee is connected to Bungee and another server, but everything I do returns `<none>`, but there are no keep alive messages in console.

Examples of what doesn't work at all:
- all bungee players
- bungee players in a server
- network variables

I'm currently using port 1333 (which is open) and the servers are connected. They're under different IPs, but there are no connection errors and syntaxes that do not require BungeeCord are working fine (send actionbar/titles to players)

Versions:
- Skript dev36
- Skungee 1.0.9
- Spigot 1.8.8

Hope this can be fixed soon.
Thanks.

**Comment by TheLimeGlass** [comment] 2019-02-07 21:04
> I am having the same problem.
> Anything that has to do with BungeeCord doesn't work. Skungee is connected to Bungee and another server, but everything I do returns `<none>`, but there are no keep alive messages in console.
> 
> Examples of what doesn't work at all:
> 
> * all bungee players
> * bungee players in a server
> * network variables
> 
> I'm currently using port 1333 (which is open) and the servers are connected. They're under different IPs, but there are no connection errors and syntaxes that do not require BungeeCord are working fine (send actionbar/titles to players)
> 
> Versions:
> 
> * Skript dev36
> * Skungee 1.0.9
> * Spigot 1.8.8
> 
> Hope this can be fixed soon.
> Thanks.

Are the players joining through the proxy? It won't work otherwise. Is the Bungeecord option on the spigot servers set to true and ipforwarding on Bungeecord config is true?

**Comment by TheLimeGlass** [comment] 2019-02-07 21:14
Some syntaxes require the receivers to be open. Asking for the host to open ports is their job and they should have been given you alot more. I want to say nearly 80% of users that have problems with Skungee use shared hosting.

Keeping this issue open as it doesn't correspond with the original.

**Comment by TrademarkTM** [comment] 2019-02-08 21:57
Which syntaxes though? None of them seem to work (only the ones like actionbars are working).

```
[Skungee] Reciever established on port 25594
```
This is the receiver port, which my host opened for that IP.
The 1333 port has been opened under another IP, which seems to be working fine (the other servers connect to it - there are no keep alive messages, but the bungee syntaxes return `<none>` every single time).

Do you have any idea about the cause of the problem?

**Comment by TheLimeGlass** [comment] 2019-02-23 21:49
What's both your heartbeat configuration value set at, and does the console state anything about servers disconnecting and/or connecting other than initial startup?

The issue is either the server is struggling to keep updating or some issue, or the server tracker doesn't contain the server.

**Comment by TheLimeGlass** [comment] 2019-02-23 22:00
Another question is, are these instances of the Spigot and Bungeecord running on a shared host or on a dedicated server, are you guys using local host as the configuration host?

**Comment by TheLimeGlass** [comment] 2019-09-05 11:52
Does this bug still persist?

**Comment by GlobooX** [comment] 2019-09-26 16:05
@TheLimeGlass 
I am from #71 
After ~20hours online of my server Skungee just stop responding and all Skungee features does not work.
Check online server, skungee send player to other server (even if server is online), network variables..
On server console i have "Connection established again" every ~1 minute. 
Maybe cause of this problem is a lot of oppened ports?

**Comment by TheLimeGlass** [comment] 2020-01-29 04:57
Fixed in 1.0.12

**Closed by TheLimeGlass** 2020-01-29 04:57 UTC
Labels: bug, investigating
